### ISSUE TITLE
Installation using CocoaPods doesn't work with use_frameworks

### ISSUE THREAD

**Issue by felipowsky** [Kong/unirest-obj-c#29]
I installed Unirest using CocoaPods.
Since my project uses a Swift library I'm using `use_frameworks!` in my `Podfile`.

![use_frameworks](https://cloud.githubusercontent.com/assets/1298990/6854643/51935ec2-d3d1-11e4-84c9-bbe50291101d.png)

By doing that Xcode can't compile my project because it can't find headers inside `HttpRequest` and `HttpResponse` folders.

![import](https://cloud.githubusercontent.com/assets/1298990/6854586/06e98e14-d3d1-11e4-8e55-c66c7b7fff16.png)

I'm receiving import errors from all the headers inside these folders.

```
HttpRequest/UNIBaseRequest.h
HttpRequest/UNIBodyRequest.h
HttpRequest/UNISimpleRequest.h

HttpResponse/UNIHTTPBinaryResponse.h
HttpResponse/UNIHTTPJsonResponse.h
HttpResponse/UNIHTTPResponse.h
HttpResponse/UNIHTTPStringResponse.h
HttpResponse/UNIJsonNode.h
```

I noticed `Unirest.framework/Headers` folder has all the headers but no folders.

As a workaround, I removed the folders from the imports.
So, for example, instead of:

```
import "HttpRequest/UNIBaseRequest.h"
```

I'm using:

```
import "UNIBaseRequest.h"
```

**Comment by zjTek** [comment]
I have the same problem too

**Comment by felipowsky** [comment]
Old issue
